# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

flutter_application_path = '../flutter_go'
load File.join(flutter_application_path, '.ios', 'Flutter', 'podhelper.rb')
target 'FlutterGo' do
#  use_frameworks!
  install_all_flutter_pods(flutter_application_path)
  pod 'SnapKit'
end
